name: "Chromatic via manual"

on: [push, pull_request]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: install
      run: |
        yarn && git status --porcelain
    - name: prep package
      run: ./scripts/rename.js storybook-chromatic
    - name: run chromatic
      run: yarn chromatic --debug
      env: # Or as an environment variable
        DEBUG: chromatic-cli
        CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
