name: "Chromatic via action-test"
on: [push, pull_request, pull_request_target, pull_request_review]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - uses: chromaui/action-test@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: gcaw1ai2dgo