name: "Chromatic via action"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn
    - uses: chromaui/action@releases/v1
      env:
        DEBUG: chromatic-cli
      with:
        appCode: ${{ secrets.CHROMATIC_APP_CODE }}
        token: ${{ secrets.GITHUB_TOKEN }}