name: "self test development-like"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build
    - uses: ./
      with: 
        appCode: 5oy3iw6rkio
        token: ${{ secrets.GITHUB_TOKEN }}
        storybookBuildDir: storybook-static
