name: "self test production-like"
on:
  pull_request:
  push:
    branches:
      - 'release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn add @storybook/react
    - uses: ./
      with: 
        appCode: ${{ secrets.CHROMATIC_APP_CODE }}
        token: ${{ secrets.GITHUB_TOKEN }}
        storybookBuildDir: storybook-static
