name: "Chromatic action self test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: |
      yarn && yarn build
    - run: yarn test
